# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e8a419e9a8af04109ec427d2ace94580b16dab4745c265ecef3a083cad4e52019cde552aee1bba0be054d3494bd7df4e896519ef9a7b2425cc7a41e94784b8

test:
  secret_key_base: 91fe55382b6f52f6e273ef31f46a2ba1c77f7e81fd7a2c29e0b4eb0cc16273a4db7bab9906de6cdcae144dc47c1572c3749f31f0e5f96d2ec28ed66b1711730b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
